### ISSUE TITLE
Unexpected token 'import'

### ISSUE THREAD

**Issue by christophetd** [mdibaiee/node-telegram-api#1]
Hi, 

I can't get the module working because of the (I'm guessing) use of ES6 features in your code. What I get when I run my code is an error _unexpected token import in index.js:1_. I have updated my version of node (now 0.12.5 running on windows 7 64 bits) and I'm using the --harmony flag.

Do you have any insights?
Thanks!

**Comment by mdibaiee** [comment]
I'm currently using babel require hook to transpile my code, this will change, a new version is coming with a better API and I will provide transpiled files so you don't have to install babel.

For now, run `npm install` in the repository root.

**Comment by mdibaiee** [comment]
see the new update.

**Comment by Hunter-Github** [comment]
The requirement isn't stated clearly in the docs, it has to be on the main README.md

**Comment by mdibaiee** [comment]
@Hunter-Github This is a common task, anyways, added it to README.
