### ISSUE TITLE
Enhancement: Way to specify Arguments reply string

### ISSUE THREAD

**Issue by guyspr** [mdibaiee/node-telegram-api#17]
Would be nice if it were possible to change the `Enter value for ${argname}` string to something nicer regarding the command you called.

For example, for a weather command it would be nice to display something like `Where do you want a forecast from?`

**Comment by mdibaiee** [comment]
I like the idea, but I just can't put time onto it. Pull-requests are welcome. Thanks!

**Comment by mdibaiee** [comment]
Fixed in #36, published as `telegram-api@0.9.0`.
