### ISSUE TITLE
BUG: Unhandled Exception on message.text???

### ISSUE THREAD

**Issue by austinhuang0131** [mdibaiee/node-telegram-api#28]
```
Unhandled: [object Promise] Reason: TypeError: Cannot read property 'text' of undefined
```
As the title said.

**Comment by mdibaiee** [comment]
More details please.

**Comment by austinhuang0131** [comment]
I am unable to provide more details, as it did not tell me which line it happened.

My source is [here](https://github.com/austinhuang0131/lydia-1/blob/master/start.js).

**Comment by mdibaiee** [comment]
@austinhuang0131 ow, I know as much as you do in this case. 🤔 

I would suggest you use `.catch` blocks everywhere (i.e. better error handling) to see where the error occurs and why.

Also, see if the error occurs on a specific message / command, so you can inspect that block of code.

**Comment by austinhuang0131** [comment]
~~1. Well, I put `bot.command(...).catch(...)` but it doesn't seem to work (not a function). I have bluebird.~~ Solved.
2. Telegram will re-send all messages that had not been handled, so this is not going to work.

Sorry about that.

**Comment by mdibaiee** [comment]
@austinhuang0131 Glad your problem was solved! :+1:
