### ISSUE TITLE
NPM Registry broke. Redo your publish.

### ISSUE THREAD

**Issue by austinhuang0131** [mdibaiee/node-telegram-api#30]
Error:
```
Error: Cannot find module 'telegram-api'
```
I have uninstalled it and reinstalled, but still same error. In fact, the index.js and source files are GONE.
![screen shot 2016-11-22 at 4 06 34 pm](https://cloud.githubusercontent.com/assets/16656689/20542028/bfc55dac-b0cd-11e6-8a3f-c5bf6990067b.png)

**Comment by mdibaiee** [comment]
I installed it just fine right now, and it's available here: https://www.npmjs.com/package/telegram-api

**Comment by austinhuang0131** [comment]
Well, if you go to [registry.npmjs.org](https://registry.npmjs.org/telegram-api/0.7.7) and navigated to the `tarball` which is the tgz file, you'll find out that it doesn't have index.js or other stuff in it.

**Comment by mdibaiee** [comment]
@austinhuang0131 oops, you are right, I forgot to re-build after merging your PR.

Published as `telegram-api@0.7.8`.
