### ISSUE TITLE
telegram-api 1.0.0 built source code does not reflect recent PR implementing correct promise chaining

### ISSUE THREAD

**Issue by laurynas-karvelis** [mdibaiee/node-telegram-api#39]
Hi mdibaiee,

I've noticed that packaged npm module version 1.0.0 does not contain up-to-date code changes from my recent PR. Has the build process actually taken the latest code? Because when I look at downloaded module built source code it seems it's transpiled against an older source code.

**Comment by mdibaiee** [comment]
Woops, sorry, you are right, I didn't run `grunt` before deploying the latest version, thanks for noting. Published `node-telegram-api@1.0.1`, feel free to re-open if the issue still persists. :grin:

**Comment by laurynas-karvelis** [comment]
Nice! Just pulled the 1.0.1, all good now. Thanks once again! :)
